config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: 'posts#index'
  get 'user/following', to: 'users#following'
  get 'user/followers', to: 'users#followers'
  get 'posts/my', to: 'posts#index', my: true
  get 'posts/following', to: 'posts#index', following: true
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
  end
  resources :profiles, only: %i[show]
  resources :relationships, only: %i[create destroy]
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :author, class_name: 'User'

  validates :body, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  has_many_attached :images

  validates :title, :description, presence: true
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, :followed_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :nickname, presence: true

  def author?(post)
    post.author = self
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:nickname]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :post, only: :create

  def create
    @comment = post.comments.new(comment_params)
    @comment.author = current_user

    return unless @comment.save

    redirect_to @comment.post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.post
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :get_post, only: %i[show new edit update destroy]

  def index
    return @posts = user_posts(current_user) if params[:my]

    @posts = params[:following] ? user_posts(current_user.following) : all_posts
  end

  def show
    @images = @post.images.paginate(page: params[:page], per_page: 1)
    @comments = @post.comments
    @comment = Comment.new
  end

  def new; end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, images: [])
  end

  def get_post
    @post = params[:id] ? Post.find(params[:id]) : Post.new
  end

  def all_posts
    Post.order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  def user_posts(author)
    Post.where(author: author).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def show
    @profile = current_user
  end
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_to root_path
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def following
    @following = current_user.following.paginate(page: params[:page], per_page: 7)
  end

  def followers
    @followers = current_user.followers.paginate(page: params[:page], per_page: 7)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comments/_comment.html.slim
div class="card mb-3 px-5 bg-transparent" style="max-width: 540px;"
  p
  div class="card-head"
  div class="row"
    div class="col-10"
      = comment.author.nickname
    div class="col-2"
      = button_to "Удалить", comment_path(comment), method: :delete, class: "btn btn-outline-danger btn-sm"
  h5= comment.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="background">
    <div class="container">
      <%= render 'shared/nav' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.slim
div class="card mb-3 border-dark bg-transparent" style="max-width: 480px;"
  div class="row g-0 align-items-center"
    div class="col-9"
      div class="card-body"
        h6 class="card-title"= post.author.nickname
        h5 class="card-text"= link_to post.title, post_path(post), class: "text-dark text-decoration-none"
    div class="col-3"
      - if current_user
        - if current_user.following?(post.author)
          = button_to "Отписаться", relationship_path(current_user.active_relationships.find_by(followed_id: post.author.id)), method: :delete, class: "btn btn-outline-success btn-sm"
        - elsif !current_user.author?(post)
          = button_to "Подписаться", relationships_path, class: "btn btn-outline-success btn-sm", params: { followed_id: post.author }

app/views/posts/edit.html.slim
p
div class="card bg-transparent"
  div class="card-body"
    = form_with model: @post do |f|
      p
        = f.label :title, "Тема поста"
        = " "
        = f.text_field :title
      p
        = f.label :description, "Текст поста"
        = " "
        = f.text_area :description, size: "40x5"
      p
        = f.label :images, "Изображения"
        = " "
        = f.file_field :images, multiple: true
      p
        = f.submit "Обновить", class: "btn btn-outline-success btn-sm"

    p
      = link_to "Назад", post_path(@post), class: "btn btn-outline-dark btn-sm"

app/views/posts/index.html.slim
div class="row"
  div class="col-2"
  div class="col-10"
    p
    div class="row"
      div class="col"
        h2 class="text-start"= "Посты пользователей"
      div class="col"
        = link_to "Все посты", root_path, class: 'btn btn-outline-info'
        - if current_user
          = " "
          = link_to "Мои посты", 'posts/my', class: 'btn btn-outline-success'
          = " "
          = link_to "Подписки", 'posts/following', class: 'btn btn-outline-primary'
    .products
      table class="table"
        tb
          p= link_to "Новый пост", new_post_path, class: "btn btn-outline-success btn-sm"
        tb
          = render @posts
      div class="digg_pagination bg-transparent"
        p= will_paginate @products

app/views/posts/new.html.slim
p
div class="card bg-transparent"
  div class="card-body"
    = form_with model: @post do |f|
      p
        = f.label :title, "Тема поста"
        = f.text_field :title
      p
        = f.label :description, "Текст поста"
        = f.text_area :description, size: "40x5"
      p
        = f.label :images, "Изображения"
        = f.file_field :images, multiple: true
      p
        = f.submit "Создать", class: "btn btn-outline-success btn-sm"

    p
      = link_to "Назад", posts_path, class: "btn btn-outline-dark btn-sm"

app/views/posts/show.html.slim
div class="row"
  div class="col-2"
  div class="col-10"
    p
    div class="card mb-3 bg-transparent" style="max-width: 640px;"
      div class="row g-0 align-items-center"
        div class="col-md-4"
          div class="text-center"
            - if @images.any?
              = image_tag(@post.images[0], size: 120)
            - else
              = "Нет изображения"
            div class="digg_pagination"
              p= will_paginate @images
        div class="col-md-8"
          div class="card-body"
            h6 class="card-title"= @post.author.nickname
            h4 class="card-text"= @post.title
            p class="card-text"= @post.description
            - if current_user == @post.author
              div class="row"
                div class="col-sm-4"
                  = link_to "Редактировать", edit_post_path(@post), class: "btn btn-outline-success btn-sm"
                div class="col-sm-4"
                  = button_to "Удалить", post_path(@post), method: :delete, class: "btn btn-outline-danger btn-sm"
            p
            = link_to "Назад", posts_path, class: "btn btn-outline-dark btn-sm"

    h5="Комментарии:"
    = render @comments

    = form_with model: [@post, @comment], local: false do |f|
      p
        = f.label :body
        = " "
        = f.text_field :body
      p= f.submit "Комментировать"

app/views/profiles/show.html.slim
p
div class="card bg-transparent"
  div class="card-header"
    h4= "Профиль #{@profile.nickname}"
  div class="card-body"
    p class="card-text"= "Email: #{@profile.email}"
    p class="card-text"
      = link_to "#{@profile.posts.count} поста(ов)", posts_my_path, class: "btn btn-outline-primary"
    p class="card-text"
      = link_to "#{@profile.following.count} подписок", user_following_path(current_user), class: "btn btn-outline-primary"
    p class="card-text"
      = link_to "#{@profile.followers.count} подписчиков", user_followers_path(current_user), class: "btn btn-outline-primary"

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
nav class="navbar navbar-dark bg-dark"
  div class='container-fluid'
    div class='navbar-brand'
      = 'Blog'
    div class='navbar-text'
      = link_to "Главная", root_path
      = ' | '
      - if user_signed_in?
        = link_to "Профиль", profile_path(current_user)
        = ' | '
        = link_to "Выйти", destroy_user_session_path, :method => :delete, remote: true
      - else
        = link_to "Войти", new_user_session_path
        = ' | '
        = link_to "Зарегистрироваться", new_user_registration_path

app/views/users/_follow.html.slim
div class="card mb-3 border-dark bg-transparent" style="max-width: 480px;"
  div class="row g-0 align-items-center"
    div class="col-8"
      div class="card-body"
        h6 class="card-title"= follow.nickname

app/views/users/followers.html.slim
p
div class="card bg-transparent"
  div class="card-header"
    h4= "Подписчики"
    p
      = render partial: "follow", collection: @followers

app/views/users/following.html.slim
p
div class="card bg-transparent"
  div class="card-header"
    h4= "Подписки"
    p
      = render partial: "follow", collection: @following